name: 'Setup Environment'
description: 'Sets up Java 21, Gradle with caching, and Bun for building the project'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
