name: Aionify Development Container
image: mcr.microsoft.com/devcontainers/base:ubuntu

features:
  ghcr.io/devcontainers/features/java:1:
    version: "21"
    installGradle: false
    installMaven: false
  ghcr.io/shyim/devcontainers-features/bun:0:
    version: latest
