ALTER TABLE goals_settings
    ADD COLUMN weekly_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN weekly_goal_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN weekly_working_days VARCHAR(128) NOT NULL DEFAULT 'MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY';
